package Hibernate;
// Generated Feb 1, 2018 2:28:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer id;
     private User user;
     private Date date;
     private Set<InvoiceItem> invoiceItems = new HashSet<InvoiceItem>(0);

    public Invoice() {
    }

	
    public Invoice(User user) {
        this.user = user;
    }
    public Invoice(User user, Date date, Set<InvoiceItem> invoiceItems) {
       this.user = user;
       this.date = date;
       this.invoiceItems = invoiceItems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<InvoiceItem> getInvoiceItems() {
        return this.invoiceItems;
    }
    
    public void setInvoiceItems(Set<InvoiceItem> invoiceItems) {
        this.invoiceItems = invoiceItems;
    }




}


