package Hibernate;
// Generated Feb 1, 2018 2:28:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * List generated by hbm2java
 */
public class List  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String type;
     private Set<ListItems> listItemses = new HashSet<ListItems>(0);

    public List() {
    }

	
    public List(User user) {
        this.user = user;
    }
    public List(User user, String type, Set<ListItems> listItemses) {
       this.user = user;
       this.type = type;
       this.listItemses = listItemses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<ListItems> getListItemses() {
        return this.listItemses;
    }
    
    public void setListItemses(Set<ListItems> listItemses) {
        this.listItemses = listItemses;
    }




}


